"""Aggregate per-dataset replay JSONs into results tables (results/summary.md, results/rows.csv)."""
import json, glob, os, re, sys
import numpy as np, pandas as pd
from scipy.stats import wilcoxon
import dendropy
R = '/home/user/scratch/cs581/iqstop/results'
TN = dendropy.TaxonNamespace()

def splits(nwk, keep=None, minlen=None):
    t = dendropy.Tree.get(data=nwk, schema='newick', preserve_underscores=True, taxon_namespace=TN)
    leaves = sorted(n.taxon.label for n in t.leaf_node_iter())
    if keep is not None:
        drop = [l for l in leaves if l not in keep]
        if drop: t.prune_taxa_with_labels(drop); leaves = sorted(keep & set(leaves))
    ref = leaves[0]; n = len(leaves); S = set()
    for nd in t.postorder_node_iter():
        if nd.is_leaf():
            nd._l = frozenset([nd.taxon.label]); continue
        nd._l = frozenset().union(*[c._l for c in nd.child_node_iter()])
        if nd.parent_node is None: continue
        if minlen is not None and (nd.edge.length or 0) <= minlen: continue
        s = nd._l if ref not in nd._l else frozenset(leaves) - nd._l
        if 1 < len(s) < n - 1: S.add(s)
    return S, n

def nrf(a, b):
    return len(a ^ b) / max(len(a) + len(b), 1)

rows = []
for f in sorted(glob.glob(f'{R}/per_dataset/*.json')):
    r = json.load(open(f)); ds = r['ds']
    grp = 'sim' if ds.startswith('rg') else ('emp-AA' if ds.startswith('empAA') else 'emp-DNA')
    trees = r['trees']; d0 = r['rules']['default(nstop100)']
    keep = None
    sp = {}
    def S(k):
        if k not in sp: sp[k] = splits(trees[k])[0]
        return sp[k]
    true = None
    if grp == 'sim':
        names = set(dendropy.Tree.get(data=trees[0], schema='newick', preserve_underscores=True).taxon_namespace.labels())
        tt = open(f"/opt/work/sim/{ds}.true.nwk").read()
        true, _ = splits(tt, keep=names, minlen=1e-5)
    entries = [(k, v) for k, v in r['rules'].items()] + [(k, v) for k, v in r['comps'].items() if k != 'iqdef1_final']
    for name, v in entries:
        if v.get('time') is None and name != 'iqdef2': continue
        if v.get('time') is None: v['time'] = float('nan')
        k = v['tree']
        if k is None:
            k = 'str:' + name; sp[k] = splits(v['tree_str'])[0]
        row = dict(ds=ds, group=grp, method=name, time=v['time'], speedup=r['wall_default'] / v['time'],
                   dlnl=v['lnl'] - d0['lnl'], au=v['au'], nrf_default=nrf(S(k), S(d0['tree'])),
                   stop_it=v.get('stop_it'), n_impr=r['n_impr'], last_it=r['last_it'], wall_default=r['wall_default'])
        if true is not None:
            row['fn_true'] = len(true - S(k)) / len(true)
            row['dfn_true'] = row['fn_true'] - len(true - S(d0['tree'])) / len(true)
        rows.append(row)
df = pd.DataFrame(rows); df.to_csv(f'{R}/rows.csv', index=False)

def summarize(sub, tie=0.5):
    out = []
    for m, g in sub.groupby('method', sort=False):
        d = g['dlnl'].values
        w = (d > tie).sum(); l = (d < -tie).sum(); t = len(d) - w - l
        try: p = wilcoxon(d).pvalue if np.any(np.abs(d) > 1e-9) else 1.0
        except Exception: p = float('nan')
        o = dict(method=m, n=len(g), gmean_speedup=float(np.exp(np.log(g['speedup']).mean())),
                 median_speedup=g['speedup'].median(), mean_dlnl=d.mean(), min_dlnl=d.min(),
                 WTL=f'{w}/{t}/{l}', wilcoxon_p=p, au_plausible=(g['au'] > 0.05).mean(),
                 mean_nrf_default=g['nrf_default'].mean())
        if 'dfn_true' in g and g['dfn_true'].notna().any():
            dd = g['dfn_true'].values
            o['mean_fn_true'] = g['fn_true'].mean(); o['mean_dfn_true'] = dd.mean()
            try: o['p_dfn'] = wilcoxon(dd).pvalue if np.any(np.abs(dd) > 1e-12) else 1.0
            except Exception: o['p_dfn'] = float('nan')
        out.append(o)
    return pd.DataFrame(out)

order = ['default(nstop100)', 'iqdef2', 'iqnstop20', 'rxclassic1', 'nstop50', 'nstop20', 'nstop10', 'KHpat100', 'KHpat50', 'KHpat20',
         'KHwin20', 'KHwin10', 'KHwin10mult', 'iqfast', 'rxfast']
md = ['# Pilot summary (auto-generated by code/aggregate.py)\n',
      'speedup = IQ-TREE default wall / method wall (replayed rules: trace time at stop + post-search time). '
      'dlnl = lnL(method tree) - lnL(default tree), both re-evaluated in one IQ-TREE -z run (same model). '
      'W/T/L on dlnl with tie band 0.5 lnL. Wilcoxon signed-rank on dlnl. AU plausible = p-AU > 0.05 among all '
      'candidate trees of the dataset. nRF to the default tree; FN to the true tree (sim only; true branches <= 1e-5 contracted).\n']
for grp in ['ALL', 'sim', 'emp-DNA', 'emp-AA']:
    sub = df if grp == 'ALL' else df[df.group == grp]
    if sub.empty: continue
    s = summarize(sub)
    s['o'] = s['method'].map({m: i for i, m in enumerate(order)}); s = s.sort_values('o').drop(columns='o')
    md.append(f'\n## {grp} (n datasets = {sub.ds.nunique()})\n')
    md.append(s.to_markdown(index=False, floatfmt='.3g'))
open(f'{R}/summary.md', 'w').write('\n'.join(md) + '\n')
print('\n'.join(md))
