# AI-assisted (Claude), exploration code for CS581 project
"""Collect gcmwhy results into markdown tables.

    python3 summarize.py [BANK]   -> cs581/gcmwhy/results/tables.md, results/merges.jsonl (copy of all rows)
"""
import json
import os
import sys

import numpy as np
from scipy import stats

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "results")
BANK = sys.argv[1] if len(sys.argv) > 1 else "/tmp/claude-0/bank"


def reps():
    out = []
    for line in open(os.path.join(HERE, "reps.tsv")):
        r, t, bb, split = line.rstrip("\n").split("\t")
        out.append((r, "protein" if t == "protein" else "nucleotide", split))
    return out


def err(row):
    return 100 * (row["SPFN"] + row["SPFP"]) / 2


def load():
    E, M = {}, {}
    rows = []
    for r, t, s in reps():
        f = os.path.join(RES, "edges", r + ".json")
        if os.path.exists(f):
            E[r] = json.load(open(f))
        f = os.path.join(BANK, r, "why_results.jsonl")
        if os.path.exists(f):
            for line in open(f):
                d = json.loads(line)
                d["rep"] = r
                M.setdefault(r, {})[d["variant"]] = d
                rows.append(d)
    with open(os.path.join(RES, "merges.jsonl"), "w") as f:
        for d in rows:
            f.write(json.dumps(d) + "\n")
    return E, M


def fmt(x, nd=2):
    return "–" if x is None or (isinstance(x, float) and np.isnan(x)) else "{:.{}f}".format(x, nd)


def mean_by(vals, types, t):
    v = [x for x, tt in zip(vals, types) if tt == t and x is not None and not np.isnan(x)]
    return (np.mean(v), len(v)) if v else (np.nan, 0)


def main():
    E, M = load()
    R = reps()
    out = ["# gcmwhy tables (generated by code/summarize.py)", "",
           "Error = (SPFN + SPFP) / 2 × 100. Δ = variant − magus (same subsets, same backbones, same merge code).",
           "Truth per edge: > 50 % of its backbone residue-pair units are reference homologies. Units = residue pairs.", ""]
    # ---------------- H1 table
    out += ["## H1: graph headroom (backbone graph, before MCL)", "",
            "| rep | type | edges | unit prec | edge prec | k≤3 share of units | of FALSE units in k≤3 | of TRUE units in k≤3 | "
            "true EDGES with k≤3 | hard-bb removes false units | hard-bb removes true units | hard-bb removes true edges |",
            "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    agg = {}
    for r, t, s in R:
        if r not in E:
            continue
        e = E[r]
        lowtrue_edges = None
        hb, e4 = e["cut_hard-bb"], e["cut_es4"]
        vals = [e["unit_prec"], e["edge_prec"], e["low_share_units"], e["low_false_of_false_units"],
                e["low_true_of_true_units"], e4["true_edges_removed_of_true"], hb["false_units_removed_of_false"],
                hb["true_units_removed_of_true"], hb["true_edges_removed_of_true"]]
        agg.setdefault(t, []).append(vals)
        out.append("| {} | {} | {:,} | ".format(r, t[:3], e["edges"]) + " | ".join(fmt(100 * v, 1) for v in vals) + " |")
    for t, v in agg.items():
        m = np.mean(v, axis=0)
        out.append("| **mean {}** (n = {}) | | | ".format(t, len(v)) + " | ".join(fmt(100 * x, 1) for x in m) + " |")
    out += ["", "All columns except edges in %. 'true EDGES with k≤3' = share of true edges es4 deletes.", ""]
    # precision by k pooled by type
    out += ["### Precision by support k (mean over reps; edge-level precision % / unit-level precision % / share of units %)", "",
            "| type | " + " | ".join("k={}".format(x) for x in ["1", "2", "3", "4-5", "6-8", "9-99"]) + " |",
            "|---|" + "---|" * 6]
    for t in ("protein", "nucleotide"):
        cells = []
        for kb in ["1", "2", "3", "4-5", "6-8", "9-99"]:
            ep = [x["edge_prec"] for r, tt, s in R if tt == t and r in E for x in E[r]["by_k"] if x["k"] == kb]
            up = [x["unit_prec"] for r, tt, s in R if tt == t and r in E for x in E[r]["by_k"] if x["k"] == kb]
            us = [x["unit_share"] for r, tt, s in R if tt == t and r in E for x in E[r]["by_k"] if x["k"] == kb]
            cells.append("{} / {} / {}".format(fmt(100 * np.mean(ep), 1), fmt(100 * np.mean(up), 1), fmt(100 * np.mean(us), 1))
                         if ep else "–")
        out.append("| {} | ".format(t) + " | ".join(cells) + " |")
    out.append("")
    out += ["### Where the TRUE and the FALSE residue-pair units sit on the support axis (% of each, mean over reps)", "",
            "| type | units | " + " | ".join("k={}".format(x) for x in ["1", "2", "3", "4-5", "6-8", "9-99"]) + " |",
            "|---|---|" + "---|" * 6]
    for t in ("protein", "nucleotide"):
        for lab in ("true", "false"):
            cells = []
            for kb in ["1", "2", "3", "4-5", "6-8", "9-99"]:
                v = []
                for r, tt, s in R:
                    if tt != t or r not in E:
                        continue
                    e = E[r]
                    tot_t = e["units"] * e["unit_prec"]
                    tot_f = e["units"] * (1 - e["unit_prec"])
                    for x in e["by_k"]:
                        if x["k"] == kb:
                            u = x["unit_share"] * e["units"]
                            v.append(u * x["unit_prec"] / tot_t if lab == "true" else u * (1 - x["unit_prec"]) / tot_f)
                cells.append(fmt(100 * np.mean(v), 1) if v else "–")
            out.append("| {} | {} | ".format(t, lab) + " | ".join(cells) + " |")
    out.append("")
    out += ["### Vote splitting: edges hard-bb deletes / keeps (mean over reps; k = own support, kp = pooled over b±1, a±1)", "",
            "| type | group | edges (mean) | mean k | mean kp | mean n |", "|---|---|---|---|---|---|"]
    for t in ("protein", "nucleotide"):
        for g in ("true_deleted", "false_deleted", "true_kept", "false_kept"):
            v = [E[r]["h2_split"][g] for r, tt, s in R if tt == t and r in E and "h2_split" in E[r]]
            if v:
                out.append("| {} | {} | {:,.0f} | {} | {} | {} |".format(t, g, np.mean([x["edges"] for x in v]),
                           *(fmt(np.mean([x[c] for x in v if x[c] is not None])) for c in ("mean_k", "mean_kp", "mean_n"))))
    out.append("")
    out += ["### Which true edges the filters delete, by the smaller node's size (residues; mean over reps)", "",
            "| type | min node size | share of true units | es4: true edges deleted % | hard-bb: true edges deleted % | "
            "hard-bb: true units deleted % | mean k | mean n |", "|---|---|---|---|---|---|---|---|"]
    for t in ("protein", "nucleotide"):
        for i, lab in enumerate(["1-1", "2-3", "4-10", "11-"]):
            v = [E[r]["h6_sizebins"][i] for r, tt, s in R if tt == t and r in E and "h6_sizebins" in E[r]]
            v = [x for x in v if x["true_edges"] > 0]
            if v:
                out.append("| {} | {} | {} | {} | {} | {} | {} | {} |".format(t, lab, *(fmt(100 * np.mean([x[c] for x in v]), 1) for c in
                           ("true_units_share", "es4_true_edges_removed", "hard-bb_true_edges_removed", "hard-bb_true_units_removed")),
                           fmt(np.mean([x["mean_k"] for x in v])), fmt(np.mean([x["mean_n"] for x in v]))))
    out.append("")
    # ---------------- H2
    out += ["## H2: near-miss false edges (offset to the nearest true partner column, share of FALSE units)", "",
            "| type | k | off 0 (partly true) | 1 | 2 | 3–5 | ≥ 6 | none |", "|---|---|---|---|---|---|---|---|"]
    for t in ("protein", "nucleotide"):
        for kb in ["1", "2", "3", "4-5", "6-8", "9-99"]:
            rows = [x for r, tt, s in R if tt == t and r in E for x in E[r]["h2_offsets_units"] if x["k"] == kb]
            if not rows:
                continue
            cols = ["off0", "off1", "off2", "off3-5", "off6-", "off_none"]
            out.append("| {} | {} | ".format(t, kb) + " | ".join(fmt(100 * np.mean([x[c] for x in rows]), 1) for c in cols) + " |")
    out += ["", "Near-miss pooling at graph level (kpool = backbones aligning a with b±1 or a±1 with b; mean over reps):", "",
            "| type | rule | true units kept % | false units kept % | precision of kept % |", "|---|---|---|---|---|"]
    for t in ("protein", "nucleotide"):
        for rule in ("k>=4", "kpool>=4", "hard-bb"):
            v = [E[r]["h2_pool"][rule] for r, tt, s in R if tt == t and r in E]
            if v:
                out.append("| {} | {} | {} | {} | {} |".format(t, rule, *(fmt(100 * np.mean([x[c] for x in v]), 1)
                                                                       for c in ("true_units_kept", "false_units_kept", "prec_kept"))))
    out.append("")
    # ---------------- merges
    var = ["es4", "hard-bb", "or-es4-false", "or-es4-true", "or-hbb-false", "or-hbb-true", "or-allfalse"]
    extra = sorted({v for r in M for v in M[r]} - set(var) - {"magus"})
    var += extra
    out += ["## Merges: Δ error vs magus (oracle splits of each filter)", "",
            "or-F-false = delete only the FALSE edges filter F deletes; or-F-true = delete only its TRUE edges; "
            "or-allfalse = delete every false edge. If filter ≈ or-F-false + or-F-true, the filter's effect is the sum of "
            "a gain from removing false edges and a loss from removing true edges.", "",
            "| rep | type | magus | " + " | ".join(var) + " |", "|---|---|---|" + "---|" * len(var)]
    D = {v: [] for v in var}
    types, RR = [], []
    for r, t, s in R:
        if r not in M or "magus" not in M[r]:
            continue
        base = err(M[r]["magus"])
        types.append(t)
        RR.append(r)
        cells = []
        for v in var:
            x = err(M[r][v]) - base if v in M[r] else np.nan
            D[v].append(x)
            cells.append(fmt(x))
        out.append("| {} | {} | {} | ".format(r, t[:3], fmt(base)) + " | ".join(cells) + " |")
    for t in ("protein", "nucleotide"):
        cells = []
        for v in var:
            m, n = mean_by(D[v], types, t)
            cells.append("{} (n={})".format(fmt(m), n))
        out.append("| **mean {}** | | | ".format(t) + " | ".join(cells) + " |")
    out.append("")
    out += ["Robust summary (BBA0081 excluded: its beta-binomial fit labels the wrong component and deletes 97 % of true "
            "units). Median Δ; Mann–Whitney p for protein vs nucleotide:", "",
            "| variant | protein median (n) | nucleotide median (n) | MW p |", "|---|---|---|---|"]
    for v in ("es4", "hard-bb", "or-es4-false", "or-es4-true", "or-hbb-false", "or-hbb-true", "or-allfalse"):
        pv = [x for x, tt, r in zip(D[v], types, RR) if tt == "protein" and r != "BBA0081" and not np.isnan(x)]
        nv = [x for x, tt, r in zip(D[v], types, RR) if tt == "nucleotide" and not np.isnan(x)]
        p = stats.mannwhitneyu(pv, nv).pvalue if pv and nv else np.nan
        out.append("| {} | {} ({}) | {} ({}) | {} |".format(v, fmt(np.median(pv)), len(pv), fmt(np.median(nv)), len(nv), fmt(p, 4)))
    out.append("")
    # SPFN / SPFP split
    out += ["### ΔSPFN / ΔSPFP (points) by type", "", "| type | variant | ΔSPFN | ΔSPFP |", "|---|---|---|---|"]
    for t in ("protein", "nucleotide"):
        for v in var:
            a = [100 * (M[r][v]["SPFN"] - M[r]["magus"]["SPFN"]) for r, tt, s in R if tt == t and r in M and v in M[r] and "magus" in M[r]]
            b = [100 * (M[r][v]["SPFP"] - M[r]["magus"]["SPFP"]) for r, tt, s in R if tt == t and r in M and v in M[r] and "magus" in M[r]]
            if a:
                out.append("| {} | {} | {} | {} |".format(t, v, fmt(np.mean(a)), fmt(np.mean(b))))
    out.append("")
    # ---------------- H4
    out += ["## H4: where the missed homologies are (cross-subset true residue pairs, % of all; mean over reps)", "",
            "miss_noedge: no backbone ever aligned the two nodes; miss_edge_dropped: an edge existed but this variant deleted it; "
            "miss_edge_kept: the edge was in the graph and MCL/trace still put the nodes in different columns.", "",
            "| type | variant | xSPFN | miss no edge | miss edge dropped | miss edge kept | MCL clusters violating % | "
            "true pairs split across MCL clusters | nodes unclustered after trace % |", "|---|---|---|---|---|---|---|---|---|"]
    for t in ("protein", "nucleotide"):
        for v in ["magus"] + var:
            rs = [M[r][v] for r, tt, s in R if tt == t and r in M and v in M[r]]
            if not rs:
                continue
            out.append("| {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(
                t, v, *(fmt(100 * np.mean([x[c] for x in rs])) for c in ("xSPFN", "miss_noedge", "miss_edge_dropped", "miss_edge_kept")),
                fmt(100 * np.mean([x["clusters"]["violating_frac"] for x in rs]), 1),
                fmt(100 * np.mean([x["clusters"]["true_pairs_split_between_clusters"] for x in rs])),
                fmt(100 * np.mean([x["trace"]["nodes_unclustered_frac"] for x in rs]))))
    out.append("")
    # ---------------- H5 paired table
    h5 = [r for r, t, s in R if r in M and "magus@f2" in M[r]]
    if h5:
        out += ["## H5: MCL inflation (MAGUS default 4) — Δ vs magus at the SAME inflation", "",
                "| rep | type | inflation | magus error | Δ es4 | Δ hard-bb | Δ or-hbb-true |", "|---|---|---|---|---|---|---|"]
        for r in h5:
            t = [tt for rr, tt, s in R if rr == r][0]
            for f in ("2", "4", "6"):
                sfx = "" if f == "4" else "@f" + f
                if "magus" + sfx not in M[r]:
                    continue
                b = err(M[r]["magus" + sfx])
                cells = [fmt(err(M[r][v + sfx]) - b) if v + sfx in M[r] else "–" for v in ("es4", "hard-bb", "or-hbb-true")]
                out.append("| {} | {} | {} | {} | ".format(r, t[:3], f, fmt(b)) + " | ".join(cells) + " |")
        out.append("")
    # ---------------- H3 regression
    feats = []
    for r, t, s in R:
        if r not in E or r not in M or "magus" not in M[r] or r == "BBA0081":
            continue
        e = E[r]
        f = {"rep": r, "protein": 1.0 if t == "protein" else 0.0, "magus_err": err(M[r]["magus"]),
             "pdist": e["feat"]["pdist"], "ref_gapfrac": e["feat"]["ref_gapfrac"], "sub_gapfrac": e["feat"]["sub_gapfrac"],
             "bb_jaccard": e["feat"]["bb_jaccard"], "low_share_units": e["low_share_units"],
             "graph_prec": e["unit_prec"], "lowk_true_edges": e["cut_es4"]["true_edges_removed_of_true"],
             "hbb_true_units_removed": e["cut_hard-bb"]["true_units_removed_of_true"],
             "hbb_false_units_removed": e["cut_hard-bb"]["false_units_removed_of_false"],
             "ntaxa": float(e["feat"]["ntaxa"])}
        for v in ("es4", "hard-bb", "or-hbb-false", "or-hbb-true"):
            f["d_" + v] = err(M[r][v]) - f["magus_err"] if v in M[r] else np.nan
        feats.append(f)
    json.dump(feats, open(os.path.join(RES, "h3_features.json"), "w"), indent=1)
    names = ["protein", "magus_err", "pdist", "ref_gapfrac", "sub_gapfrac", "bb_jaccard", "low_share_units", "graph_prec",
             "lowk_true_edges", "hbb_true_units_removed", "hbb_false_units_removed", "ntaxa"]
    out += ["## H3: what the filter gain tracks (Spearman ρ across reps, BBA0081 excluded; p in parentheses)", "",
            "| feature | Δ es4 | Δ hard-bb | Δ or-hbb-false (gain part) | Δ or-hbb-true (loss part) |", "|---|---|---|---|---|"]
    for nm in names:
        cells = []
        for v in ("d_es4", "d_hard-bb", "d_or-hbb-false", "d_or-hbb-true"):
            x = np.array([f[nm] for f in feats]); y = np.array([f[v] for f in feats])
            ok = ~np.isnan(y)
            if ok.sum() >= 5:
                rho, p = stats.spearmanr(x[ok], y[ok])
                cells.append("{} ({})".format(fmt(rho), fmt(p, 3)))
            else:
                cells.append("–")
        out.append("| {} | ".format(nm) + " | ".join(cells) + " |")
    out.append("")
    # multivariable: d_hard-bb ~ protein + feature (OLS), one feature at a time
    out += ["### OLS: Δ hard-bb ~ protein + feature (does the data-type effect survive a difficulty covariate?)", "",
            "| feature | coef protein (p) | coef feature (p) | R² |", "|---|---|---|---|"]
    for nm in names[1:]:
        X = np.array([[1.0, f["protein"], f[nm]] for f in feats if not np.isnan(f["d_hard-bb"])])
        y = np.array([f["d_hard-bb"] for f in feats if not np.isnan(f["d_hard-bb"])])
        if len(y) < 6:
            continue
        Xs = X.copy()
        Xs[:, 2] = (Xs[:, 2] - Xs[:, 2].mean()) / (Xs[:, 2].std() + 1e-12)
        beta, *_ = np.linalg.lstsq(Xs, y, rcond=None)
        res = y - Xs @ beta
        dof = len(y) - 3
        s2 = res @ res / dof
        cov = s2 * np.linalg.inv(Xs.T @ Xs)
        se = np.sqrt(np.diag(cov))
        p = 2 * stats.t.sf(np.abs(beta / se), dof)
        r2 = 1 - res @ res / ((y - y.mean()) @ (y - y.mean()))
        out.append("| {} (per SD) | {} ({}) | {} ({}) | {} |".format(nm, fmt(beta[1]), fmt(p[1], 3), fmt(beta[2]), fmt(p[2], 3), fmt(r2)))
    out.append("")
    open(os.path.join(RES, "tables.md"), "w").write("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
