# AI-assisted (Claude), exploration code for CS581 project
"""Tables for REPORT.md from /opt/work/gcmvote/reps/*/{results.jsonl,calib.json,trees.jsonl}.

    python3 summarize.py > ../results/tables.md     (also copies raw rows to ../results/raw/)
"""
import glob
import json
import os
import shutil
import sys

import numpy as np
from scipy.stats import wilcoxon

W = "/opt/work/gcmvote/reps"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "results")
TRAIN = ["BBA0101", "BBA0134", "BBA0067", "BBA0039", "SIMMOD_R1", "SIMHIGH_R1", "1000M2", "1000L1", "1000L2", "16S.M"]
HELD = ["BBA0154", "BBA0190", "SIMMOD_R2", "SIMHIGH_R2", "1000L3", "1000M3", "1000S1", "1000S2", "RNASim", "1000M4",
        "1000S3", "1000M2_R1", "1000L1_R1", "RNASim_R1"]
VOTE = ["hard", "soft", "soft2", "soft4", "hard-bb", "soft-bb"]
SELECTED = os.environ.get("SELECTED", "")


def is_prot(r):
    return r.startswith(("BBA", "SIM"))


rows = {}
for f in glob.glob(os.path.join(W, "*", "results.jsonl")):
    for l in open(f):
        d = json.loads(l)
        rows[(d["rep"], d["variant"], d["B"])] = d
# held-out replicates this branch did not draw: helper rows (same vote.py, their own MAGUS draw)
HELPER_ALN = {}
for f in glob.glob(os.path.join(OUT, "helpers", "*.vote.results.jsonl")):
    for l in open(f):
        d = json.loads(l)
        if not any(k[0] == d["rep"] for k in rows):
            HELPER_ALN.setdefault(d["rep"], os.path.basename(f).split(".")[0])
            rows[(d["rep"], d["variant"], d["B"])] = d
os.makedirs(os.path.join(OUT, "raw"), exist_ok=True)
for f in glob.glob(os.path.join(W, "*", "*.jsonl")) + glob.glob(os.path.join(W, "*", "calib*.json")):
    shutil.copy(f, os.path.join(OUT, "raw", os.path.basename(os.path.dirname(f)) + "." + os.path.basename(f)))
for f in glob.glob(os.path.join(W, "*", "vote", "*", "model.json")):
    p = f.split(os.sep)
    shutil.copy(f, os.path.join(OUT, "raw", "{}.{}.model.json".format(p[-4], p[-2])))


def err(rep, v, B=10):
    d = rows.get((rep, v, B))
    if d is None and v == "frac0.4" and B == 10:
        d = rows.get((rep, "es4", 10))  # identical rule: k >= ceil(0.4 * 10)
    return None if d is None else 100 * d["avgErr"]


def delta(rep, v, base="magus", B=10, Bbase=None):
    a, b = err(rep, v, B), err(rep, base, Bbase or B)
    return None if a is None or b is None else a - b


def stats(ds):
    ds = [d for d in ds if d is not None]
    if not ds:
        return "–"
    w = sum(d < -0.05 for d in ds); l = sum(d > 0.05 for d in ds); t = len(ds) - w - l
    p = wilcoxon(ds).pvalue if len(ds) > 1 and any(abs(d) > 0 for d in ds) else float("nan")
    return "{:+.2f} ({}/{}/{}, p = {:.3f}), n = {}".format(np.mean(ds), w, t, l, p, len(ds))


def ftab(reps, variants, base="magus", B=10):
    print("| replicate | {} error % | {} |".format(base, " | ".join(variants)))
    print("|---|---|" + "---|" * len(variants))
    for r in reps:
        if err(r, base, B) is None:
            continue
        cells = ["{:+.2f}".format(delta(r, v, base, B)) if delta(r, v, base, B) is not None else "–" for v in variants]
        print("| {} | {:.2f} | {} |".format(r, err(r, base, B), " | ".join(cells)))
    for lab, sel in (("proteins", is_prot), ("DNA/RNA", lambda r: not is_prot(r)), ("all", lambda r: True)):
        print("| **{}** | | {} |".format(lab, " | ".join(stats([delta(r, v, base, B) for r in reps if sel(r)]) for v in variants)))
    print()


print("# gcmvote tables (generated by code/summarize.py)\n")
if HELPER_ALN:
    print("Rows from helper branches (their own MAGUS draw, same vote.py): {}\n".format(HELPER_ALN))
print("Δ = variant − baseline, error points ((SPFN+SPFP)/2 × 100). Summary cells: mean Δ (W/T/L at 0.05, Wilcoxon p), n.\n")
print("## Training (B = 10)\n")
ftab(TRAIN, ["es4"] + VOTE)
print("## Held-out (B = 10)\n")
ftab(HELD, ["es4"] + VOTE)
if SELECTED:
    print("## Held-out: selected `{}` vs es4\n".format(SELECTED))
    ftab(HELD, [SELECTED], base="es4")
    print("## Training: selected `{}` vs es4\n".format(SELECTED))
    ftab(TRAIN, [SELECTED], base="es4")

# SPFN / SPFP
print("## Mean ΔSPFN / ΔSPFP (×100) vs magus\n")
print("| variant | train prot | train DNA/RNA | held prot | held DNA/RNA |")
print("|---|---|---|---|---|")
for v in ["es4"] + VOTE:
    cells = []
    for reps in (TRAIN, HELD):
        for sel in (is_prot, lambda r: not is_prot(r)):
            fn = [100 * (rows[(r, v, 10)]["SPFN"] - rows[(r, "magus", 10)]["SPFN"]) for r in reps if sel(r) and (r, v, 10) in rows and (r, "magus", 10) in rows]
            fp = [100 * (rows[(r, v, 10)]["SPFP"] - rows[(r, "magus", 10)]["SPFP"]) for r in reps if sel(r) and (r, v, 10) in rows and (r, "magus", 10) in rows]
            cells.append("{:+.2f} / {:+.2f}".format(np.mean(fn), np.mean(fp)) if fn else "–")
    print("| {} | {} |".format(v, " | ".join(cells)))
print()

# effective cutoffs
print("## Effective cutoff chosen by the model (smallest k with w > 0.5 at full exposure n = B), B = 10\n")
print("| replicate | split | binomial: p1 / p0 / π | cutoff n=10 (binom) | cutoff n=10 (BB) | cutoffs n=5..9 (binom) | share of edges with n = 10 | hard keeps edges |")
print("|---|---|---|---|---|---|---|---|")
for r in TRAIN + HELD:
    f = os.path.join(W, r, "vote", "hard", "model.json")
    g = os.path.join(W, r, "vote", "hard-bb", "model.json")
    if not os.path.exists(f):
        continue
    m = json.load(open(f)); mb = json.load(open(g)) if os.path.exists(g) else {"cutoff_by_n": {}}
    fb = m["fit"]["binom"]
    nh = m["n_hist"]
    print("| {} | {} | {:.2f} / {:.2f} / {:.2f} | {} | {} | {} | {:.2f} | {:.2f} |".format(
        r, "train" if r in TRAIN else "held", fb["p1"], fb["p0"], fb["pi"], m["cutoff_by_n"].get("10"),
        mb["cutoff_by_n"].get("10"), ",".join(str(m["cutoff_by_n"].get(str(n))) for n in range(5, 10)),
        nh.get("10", 0) / sum(nh.values()), m["kept_edges"] / m["edges"]))
print()

# fit quality
print("## Mixture fit quality (G statistic of the (k, n) table, BIC), B = 10\n")
print("| replicate | cells | G binomial | G beta-binomial | ΔBIC (bb − binom) |")
print("|---|---|---|---|---|")
for r in TRAIN + HELD:
    f = os.path.join(W, r, "vote", "hard", "model.json")
    if not os.path.exists(f):
        continue
    m = json.load(open(f))["fit"]
    print("| {} | {} | {:.0f} | {:.0f} | {:.0f} |".format(r, m["binom"]["cells"], m["binom"]["G"], m["bb"]["G"], m["bb"]["bic"] - m["binom"]["bic"]))
print()

# calibration
print("## Calibration (reference used; diagnostic only), B = 10\n")
print("Edge-level precision = share of edges whose backbone residue-pair units are mostly true homologies.\n")
print("| replicate | ECE binom | ECE bb | binom bins: mean posterior → edge precision (edges) | hard keeps % of true units | precision of kept units | precision of all units |")
print("|---|---|---|---|---|---|---|")
pooled = {}
for r in TRAIN + HELD:
    f = os.path.join(W, r, "calib.json")
    if not os.path.exists(f):
        continue
    o = json.load(open(f))
    bins = "; ".join("{:.2f}→{:.2f} ({})".format(b["mean_post"], b["edge_prec"], b["edges"]) for b in o["post_binom"])
    allprec = sum(b["unit_prec"] * 1 for b in o["by_k"])  # placeholder not used
    units = sum(x["edges"] for x in o["by_k"])
    print("| {} | {:.3f} | {:.3f} | {} | {:.1f} | {:.3f} | |".format(r, o["post_binom_ece"], o["post_bb_ece"], bins,
                                                               100 * o["post_binom_kept_true_frac"], o["post_binom_kept_prec"]))
    for kind in ("post_binom", "post_bb"):
        for b in o[kind]:
            key = (kind, tuple(b["bin"]))
            p = pooled.setdefault(key, [0, 0.0, 0.0])
            p[0] += b["edges"]; p[1] += b["edges"] * b["mean_post"]; p[2] += b["edges"] * b["edge_prec"]
print()
print("### Pooled reliability table (all calibrated replicates, edges pooled)\n")
print("| posterior bin | binom: edges | mean posterior | edge precision | bb: edges | mean posterior | edge precision |")
print("|---|---|---|---|---|---|---|")
for lo in np.round(np.arange(0, 1, 0.1), 1):
    key = (round(float(lo), 1), round(float(lo) + 0.1, 1))
    cells = []
    for kind in ("post_binom", "post_bb"):
        p = pooled.get((kind, key))
        cells.append("{} | {:.2f} | {:.2f}".format(p[0], p[1] / p[0], p[2] / p[0]) if p else "0 | – | –")
    print("| {:.1f}–{:.1f} | {} |".format(key[0], key[1], " | ".join(cells)))
print()

# sensitivity
Bs = sorted({k[2] for k in rows})
sv = ["frac0.2", "frac0.3", "frac0.4", "frac0.5", "hard", "hard-bb", "es4"]
reps_s = [r for r in TRAIN + HELD if any((r, v, B) in rows for v in sv for B in Bs if B != 10)]
if reps_s:
    print("## Sensitivity to the number of backbones B (merge-only, same subsets; Δ vs magus with the same B)\n")
    for B in Bs:
        print("### B = {}\n".format(B))
        ftab(reps_s, sv, B=B)
    print("### magus with B backbones vs magus with 10 (error points)\n")
    print("| replicate | " + " | ".join("B={}".format(B) for B in Bs) + " |")
    print("|---|" + "---|" * len(Bs))
    for r in reps_s:
        print("| {} | {} |".format(r, " | ".join("{:+.2f}".format(delta(r, "magus", "magus", B, 10)) if delta(r, "magus", "magus", B, 10) is not None else "–" for B in Bs)))
    print()
    print("### Cutoff chosen by the binomial model at full exposure, per B\n")
    print("| replicate | " + " | ".join("B={}".format(B) for B in Bs) + " |")
    print("|---|" + "---|" * len(Bs))
    for r in reps_s:
        cells = []
        for B in Bs:
            d = rows.get((r, "hard", B))
            cells.append("{} / {}".format(d["cutoff_by_n"].get(str(B)), B) if d else "–")
        print("| {} | {} |".format(r, " | ".join(cells)))
    print()

# trees
tr = []
for f in glob.glob(os.path.join(W, "*", "trees.jsonl")):
    tr += [json.loads(l) for l in open(f)]
for f in glob.glob(os.path.join(OUT, "helpers", "*.trees.jsonl")):
    tr += [dict(json.loads(l), helper=os.path.basename(f)) for l in open(f)]
if tr:
    print("## Trees: FastTree -lg -gamma nRF (%) vs the true tree\n")
    T = {}
    for d in tr:
        T[(d["dataset"], d["method"])] = 100 * d["RF"]
    ds = sorted({d for d, _ in T}, key=lambda x: (x.split("_R")[0], int(x.split("_R")[1])))
    ms = sorted({m for _, m in T}, key=lambda m: ["true", "magus"].index(m) if m in ("true", "magus") else 2)
    print("| dataset | " + " | ".join(ms) + " |")
    print("|---|" + "---|" * len(ms))
    for d in ds:
        print("| {} | {} |".format(d, " | ".join("{:.2f}".format(T[(d, m)]) if (d, m) in T else "–" for m in ms)))
    print()
    print("| method | Δ nRF vs magus: mean (W/T/L at 0.1, Wilcoxon p), n |")
    print("|---|---|")
    for m in ms:
        if m == "magus":
            continue
        dd = [T[(d, m)] - T[(d, "magus")] for d in ds if (d, m) in T and (d, "magus") in T]
        if dd:
            w = sum(x < -0.1 for x in dd); l = sum(x > 0.1 for x in dd)
            p = wilcoxon(dd).pvalue if len(dd) > 1 and any(dd) else float("nan")
            print("| {} | {:+.2f} ({}/{}/{}, p = {:.3f}), n = {} |".format(m, np.mean(dd), w, len(dd) - w - l, l, p, len(dd)))
    print()
