"""Tables for REPORT.md from results/*.results.jsonl and results/*.agree.jsonl.

    python3 summarize.py [RESULTS_DIR] > ../results/tables.md

Delta = variant - MAGUS's own merge (variant 'linsi') on the same replicate, in error points
(error = (SPFN + SPFP) / 2 x 100). W/T/L: |delta| < 0.05 is a tie; p: two-sided Wilcoxon signed-rank.
"""
import collections
import glob
import json
import os
import sys

import numpy as np
from scipy.stats import wilcoxon

R = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "results")
PROT = ("BBA", "SIM")


def kind(rep):
    return "protein" if rep.startswith(PROT) else "DNA/RNA"


rows = collections.defaultdict(dict)
for f in glob.glob(os.path.join(R, "*.results.jsonl")):
    for l in open(f):
        r = json.loads(l)
        rows[r["rep"]][r["variant"]] = r
agree = collections.defaultdict(dict)
for f in glob.glob(os.path.join(R, "*.agree.jsonl")):
    for l in open(f):
        r = json.loads(l)
        agree[r["rep"]][r["tool"]] = r

reps = sorted(rows, key=lambda r: (kind(r), r))
variants = []
for r in reps:
    for v in rows[r]:
        if v not in variants:
            variants.append(v)


def d(r, v, k="avgErr"):
    return 100 * (rows[r][v][k] - rows[r]["linsi"][k])


def stat(ds):
    ds = np.array(ds)
    w, t, l = int((ds < -0.05).sum()), int((abs(ds) <= 0.05).sum()), int((ds > 0.05).sum())
    p = wilcoxon(ds).pvalue if len(ds) >= 2 and np.any(ds != 0) else float("nan")
    return "{:+.2f}".format(ds.mean()), "{}/{}/{}".format(w, t, l), "{:.3f}".format(p)


print("# gcmgen tables (generated by code/summarize.py)\n")
print("## Per variant, by data type\n")
print("| variant | type | n | mean Δ | W/T/L | p | Δ SPFN | Δ SPFP |")
print("|---|---|---|---|---|---|---|---|")
for v in variants:
    if v == "linsi":
        continue
    for k in ("protein", "DNA/RNA"):
        rs = [r for r in reps if kind(r) == k and v in rows[r] and "linsi" in rows[r]]
        if not rs:
            continue
        m, wtl, p = stat([d(r, v) for r in rs])
        print("| `{}` | {} | {} | {} | {} | {} | {:+.2f} | {:+.2f} |".format(
            v, k, len(rs), m, wtl, p, np.mean([d(r, v, "SPFN") for r in rs]), np.mean([d(r, v, "SPFP") for r in rs])))
    rs = [r for r in reps if v in rows[r] and "linsi" in rows[r]]
    if len({kind(r) for r in rs}) == 2:
        m, wtl, p = stat([d(r, v) for r in rs])
        print("| `{}` | **all** | {} | {} | {} | {} | | |".format(v, len(rs), m, wtl, p))

print("\n## Per replicate (Δ error points; first row = MAGUS's error %)\n")
print("| variant | " + " | ".join(reps) + " |")
print("|---|" + "---|" * len(reps))
print("| MAGUS (`linsi`) | " + " | ".join("{:.2f}".format(100 * rows[r]["linsi"]["avgErr"]) if "linsi" in rows[r] else ""
                                         for r in reps) + " |")
for v in variants:
    if v == "linsi":
        continue
    print("| `{}` | ".format(v) + " | ".join("{:+.2f}".format(d(r, v)) if v in rows[r] and "linsi" in rows[r] else ""
                                           for r in reps) + " |")

print("\n## Agreement of MAGUS's L-INS-i backbones with each second aligner (cross-subset pairs)\n")
print("overlap = fraction of L-INS-i pairs the tool also aligns (mean over the 10 backbones; reference-free). "
      "support = bbevidence's support of the unconfirmed pairs (reference-free). prec_* use the reference "
      "(diagnostic only): precision of all / confirmed / unconfirmed L-INS-i pairs and of the tool's own pairs. "
      "s/bb = mean seconds per backbone (4 backbones in parallel, 4 MAFFT threads each).\n")
print("| rep | tool | overlap | min | support unconf | prec L | prec conf | prec unconf | prec tool | tool/L pairs | s/bb |")
print("|---|---|---|---|---|---|---|---|---|---|---|")
for r in reps:
    for t, a in agree.get(r, {}).items():
        print("| {} | {} | {:.3f} | {:.3f} | {:.3f} | {:.3f} | {:.3f} | {:.3f} | {:.3f} | {:.2f} | {} |".format(
            r, t, a["overlap"], a["overlap_min"], a["support_unconf"], a["prec_linsi"], a["prec_conf"], a["prec_unconf"],
            a["prec_tool"], a["pairs_tool_over_linsi"], a["bb_mean_s"]))
