# AI-assisted (Claude), exploration code for CS581 project
"""Tables for gcmvote2 from REP/results2.jsonl files.

    python3 summarize2.py OUT.md [--heldout] [--all-variants]

Δ = variant − baseline in error points ((SPFN+SPFP)/2 × 100); W/T/L with tie band ±0.1; two-sided Wilcoxon.
"""
import json
import os
import sys

import numpy as np
from scipy.stats import wilcoxon

R = "/opt/work/reps"
TRAIN = [("BBA0101", "BBA0101"), ("BBA0134", "BBA0134"), ("BBA0067", "BBA0067"), ("BBA0039", "BBA0039"),
         ("SIMMOD_R1", "bank/SIMMOD_R1"), ("SIMHIGH_R1", "bank/SIMHIGH_R1"), ("1000M2", "1000M2"),
         ("1000L1", "1000L1"), ("1000L2", "1000L2"), ("16S.M", "16S.M")]
HELD_P = [(n, "bank/" + n) for n in ("SIMMOD_R2", "SIMHIGH_R2", "BBA0154", "BBA0190", "BBA0117", "HF_blmb",
                                     "HF_aat", "HF_Acetyltransf", "HF_PDZ")]
HELD_D = [(n.replace("_R0", ""), "bank/" + n) for n in (
    "1000L3_R0", "1000M3_R0", "1000S1", "1000S2", "1000M4", "1000S3", "1000M2_R1", "1000L1_R1", "RNASim",
    "RNASim_R1", "1000M1_R0", "1000M1_R1", "1000M1_R2", "1000M1_R3", "16S.3")]
B81 = [("BBA0081", "bank/BBA0081")]
SIMB = [("SIMHIGH_R%d" % i, "bank/SIMHIGH_R%d" % i) for i in list(range(3, 13)) + list(range(14, 21))]
PROT = {"BBA", "SIM", "HF_"}
CANDS = ["m1-gbb", "m1-dm", "m1-dm-soft", "m2-ds", "m2-ds-soft", "m2-dsg", "m3-ovbb", "m23-ovds", "m4-gmm",
         "m4-gmm-soft"]
BASE = ["es4", "hard-bb"]


def load(path):
    p = os.path.join(R, path, "results2.jsonl")
    if not os.path.exists(p):
        return {}
    return {json.loads(l)["variant"]: json.loads(l) for l in open(p)}


def err(row):
    return 100 * row["avgErr"]


def stat(d):
    d = np.array(d)
    if len(d) == 0:
        return "–"
    w, t, l = int((d < -0.1).sum()), int((abs(d) <= 0.1).sum()), int((d > 0.1).sum())
    p = wilcoxon(d).pvalue if len(d) > 1 and np.any(d != 0) else float("nan")
    return "{:+.2f} (med {:+.2f}; {}/{}/{}, p = {:.3f}), n = {}".format(d.mean(), np.median(d), w, t, l, p, len(d))


def table(reps, variants, base="magus", groups=None):
    rows = [(n, load(p)) for n, p in reps]
    rows = [(n, r) for n, r in rows if base in r]
    out = ["| replicate | {} error % | {} |".format(base, " | ".join(variants)),
           "|---" * (len(variants) + 2) + "|"]
    for n, r in rows:
        cells = ["{:+.2f}".format(err(r[v]) - err(r[base])) if v in r else "–" for v in variants]
        out.append("| {} | {:.2f} | {} |".format(n, err(r[base]), " | ".join(cells)))
    groups = groups or [("all", lambda n: True)]
    for g, f in groups:
        cells = [stat([err(r[v]) - err(r[base]) for n, r in rows if f(n) and v in r]) for v in variants]
        out.append("| **{}** | | {} |".format(g, " | ".join(cells)))
    return "\n".join(out)


def deltas(reps, v, base):
    out = {}
    for n, p in reps:
        r = load(p)
        if v in r and base in r:
            out[n] = err(r[v]) - err(r[base])
    return out


is_prot = lambda n: n[:3] in PROT
GROUPS = [("proteins", is_prot), ("DNA/RNA", lambda n: not is_prot(n)), ("all", lambda n: True)]


def main():
    out = sys.argv[1]
    held = "--heldout" in sys.argv
    sel = None
    for a in sys.argv:
        if a.startswith("--selected="):
            sel = a.split("=", 1)[1]
    md = ["# gcmvote2 tables (generated by code/summarize2.py)", "",
          "Δ = variant − baseline, error points ((SPFN+SPFP)/2 × 100). Summary cells: mean Δ (median; W/T/L at "
          "±0.1, two-sided Wilcoxon p), n.", ""]
    md += ["## Training (B = 10), Δ vs magus", "", table(TRAIN, BASE + CANDS, "magus", GROUPS), "",
           "## Training, Δ vs es4", "", table(TRAIN, ["hard-bb"] + CANDS, "es4", GROUPS), ""]
    if held:
        HP = HELD_P + HELD_D
        md += ["## Held-out primary (proteins n = 9, DNA/RNA n = 15), Δ vs magus", "",
               table(HP, BASE + CANDS, "magus", GROUPS), "",
               "## Held-out primary, Δ vs es4", "", table(HP, ["hard-bb"] + CANDS, "es4", GROUPS), "",
               "## Held-out primary, Δ vs hard-bb", "", table(HP, CANDS, "hard-bb", GROUPS), "",
               "## BBA0081 (195 sequences; every backbone holds all sequences)", "",
               table(B81, BASE + CANDS, "magus"), "",
               "## Proteins incl. BBA0081, Δ vs es4", "",
               table(HELD_P + B81, ["hard-bb"] + CANDS, "es4", [("proteins + BBA0081", lambda n: True)]), "",
               "## Secondary: SIMHIGH bank (R3–R12, R14–R20), Δ vs magus", "",
               table(SIMB, BASE + CANDS, "magus"), "",
               "## Secondary: SIMHIGH bank, Δ vs es4", "", table(SIMB, ["hard-bb"] + CANDS, "es4"), ""]
    open(out, "w").write("\n".join(md) + "\n")
    print("\n".join(md))


if __name__ == "__main__":
    main()
